// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yofrfpgyhbcyqavcbxfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZnJmcGd5aGJjeXFhdmNieGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MzMwODksImV4cCI6MjA4ODQwOTA4OX0.PS5RUtOFrJLKojUZFoWtrvzVRUyQ2w-sDJ5jsZfaRzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});